---
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: main.go
    binary: kubenurse
    id: kubenurse
docker_manifests:
  - name_template: postfinance/kubenurse:{{ .Tag }}
    image_templates:
      - postfinance/kubenurse:{{ .Tag }}-amd64
      - postfinance/kubenurse:{{ .Tag }}-arm64v8
  - name_template: postfinance/kubenurse:latest
    image_templates:
      - postfinance/kubenurse:latest-amd64
      - postfinance/kubenurse:latest-arm64v8
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - kubenurse
    image_templates:
      - "postfinance/kubenurse:latest-amd64"
      - "postfinance/kubenurse:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - goos: linux
    goarch: arm64
    ids:
      - kubenurse
    image_templates:
      - "postfinance/kubenurse:latest-arm64v8"
      - "postfinance/kubenurse:{{ .Tag }}-arm64v8"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
